services:
  waystation:
    build: .
    image: waystation
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      WAYSTATION_INSTANCE_ID: ${WAYSTATION_INSTANCE_ID:-}
      WAYSTATION_PUBLIC_URL: ${WAYSTATION_PUBLIC_URL:-}
    volumes:
      - ${WAYSTATION_DATA_DIR:-./data}:/data