services:
  waystation:
    build: .
    image: waystation
    restart: "no"
    ports:
      - "3000:${WAYSTATION_PORT:-3000}"
    environment:
      WAYSTATION_INSTANCE_ID: ${WAYSTATION_INSTANCE_ID:-}
      WAYSTATION_PUBLIC_URL: ${WAYSTATION_PUBLIC_URL:-}
      WAYSTATION_LOG_LEVEL: ${WAYSTATION_LOG_LEVEL:-}
      WAYSTATION_GC_SCHEDULE: ${WAYSTATION_GC_SCHEDULE:-}
      WAYSTATION_UPLOAD_EXPIRY_DAYS: ${WAYSTATION_UPLOAD_EXPIRY_DAYS:-}
      WAYSTATION_PORT: ${WAYSTATION_PORT:-}
      WAYSTATION_UPLOAD_TOKEN: ${WAYSTATION_UPLOAD_TOKEN:-}
    volumes:
      - ${WAYSTATION_DATA_DIR:-./waystation-data}:/waystation-data